### Create emp
POST https://mern-employees-app.onrender.com/employees
Content-Type: application/json

{
    "empname":"Krishnaveni",
    "email":"krish@mail.com",
    "mobile":9999999,
    "designation":"developer",
    "companyName":"JPMC"
}

### Read all emps
GET https://mern-employees-app.onrender.com/employees

### Update emp by id
PUT https://mern-employees-app.onrender.com/employees/
Content-Type: application/json

{
    "empname":"Krishnaveni",
    "email":"krish@mail.com",
    "mobile":9999999,
    "designation":"developer",
    "companyName":"JPMC"
}

### Delete emp by id
DELETE https://mern-employees-app.onrender.com/employees/